### ISSUE TITLE
IEEE 802.11 band issue while compiling....

### ISSUE THREAD

**Issue by theimprobableoneATSH** [libxzr/android_kernel_zuk_msm8996#1]
1.
https://github.com/celtare21/kernel_essential_msm8998-1/commit/636023aa9defb80a562785de5598dd28f0c81d13#diff-06d67238b2dbb0cb9b2ac8c3f3595319

2.
https://github.com/celtare21/kernel_essential_msm8998-1/commit/45600fc5357ed79b972287958e7c861b650f65d3#diff-48836d80a02bff784b3117af669245f2

Add this commits to the kernel.lnx.4.4.r37-rel in order to fix the issue of IEEE802.11 while compiling the kernel.....

**Comment by libxzr** [comment]
I dont meet this problem while compiling.Are you using the correct toolchain?

**Comment by theimprobableoneATSH** [comment]
Yes , I have been using aarch64-linux-android-4.9

**Comment by theimprobableoneATSH** [comment]
Also have tried only gcc toolchain
